main: Reservation.o Flight.o ReservationSystem.o main.o
	g++ -o main Reservation.o Flight.o ReservationSystem.o main.o

Reservation.o: Reservation.cpp
	g++ -c Reservation.cpp

Flight.o: Flight.cpp
	g++ -c Flight.cpp

ReservationSystem.o: ReservationSystem.cpp
	g++ -c ReservationSystem.cpp

main.o: main.cpp
	g++ -c main.cpp