main: FirstAlgorithm.o SecondAlgorithm.o main.o
	g++ -o main FirstAlgorithm.o SecondAlgorithm.o main.o

FirstAlgorithm.o: FirstAlgorithm.cpp
	g++ -c FirstAlgorithm.cpp

SecondAlgorithm.o: SecondAlgorithm.cpp
	g++ -c SecondAlgorithm.cpp

main.o: main.cpp
	g++ -c main.cpp