main: SimpleStudent.o SimpleLibrarySystem.o simplemain.o
	g++ -o main SimpleStudent.o SimpleLibrarySystem.o simplemain.o


SimpleStudent.o: SimpleStudent.cpp
	g++ -c SimpleStudent.cpp

SimpleLibrarySystem.o: SimpleLibrarySystem.cpp
	g++ -c SimpleLibrarySystem.cpp

simplemain.o: simplemain.cpp
	g++ -c simplemain.cpp